# Generated by Django 4.2.3 on 2023-07-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0002_expensecategory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
