# Generated by Django 4.2.3 on 2023-07-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0003_alter_expensecategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='name',
        ),
    ]
